# kind-ingress.yaml
# Creates a single‑node kind cluster with:
#  • host 80  → container 80   (Ingress HTTP)
#  • host 443 → container 443  (Ingress HTTPS)
#  • host 8080 → container 443 (convenience port for Argo CD UI)
# It also pre‑labels the node so the ingress‑nginx manifest schedules cleanly.

kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      # Ingress HTTP
      - containerPort: 80
        hostPort: 80
      # Ingress HTTPS
      - containerPort: 443
        hostPort: 443
      # Argo CD UI on https://localhost:8080
      - containerPort: 443
        hostPort: 8080

    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"   # required by the kind ingress manifest
